# Generated by Django 4.0.4 on 2022-05-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
    ]
